### ISSUE TITLE
[User feedback] Incorrect Calcs in MER

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#133]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/report

It looks like the calculations could be off in the MER.  There should be the target and actual for the month.  And then the sum of target and actual to date.  The month total for people indicators should pull new+returning.  The to date total for people indicators should pull new only across time.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595441209166970092.png )

**Comment by adrianq** [comment]
Not sure we understand what the problem is... It seems to be doing exactly what you have just said:

MER:
![image](https://user-images.githubusercontent.com/6850223/88277012-e88fe200-ccd7-11ea-88e1-85fec5d2e642.png)

Target and Actual are calculated using this data:
![image](https://user-images.githubusercontent.com/6850223/88277097-0c532800-ccd8-11ea-869a-0dbe0332f444.png)

![image](https://user-images.githubusercontent.com/6850223/88277124-1c6b0780-ccd8-11ea-8dc9-f2f74e427e5b.png)

and the expected result is exactly what we are getting: 45 for target and 10 for actual.

If we analyze the 'to date' as you said 'The to date total for people indicators should pull new only across time.' So we go into the previous months (only July in this case) this is what we have:
![image](https://user-images.githubusercontent.com/6850223/88277290-62c06680-ccd8-11ea-9e2b-c2785d4afef3.png)
![image](https://user-images.githubusercontent.com/6850223/88277320-6fdd5580-ccd8-11ea-8193-e72288db92c0.png)

and the result is again what we can see in the MER. For target and new: 5 +5. For actual and new: 5 + 5.

Are we missing anything?

**Comment by adrianq** [comment]
@PMT will review the calculation and come back
