### ISSUE TITLE
[User feedback] Unable to add Target/Actual Values for non-PM Admin Users

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#149]
## dhis2

Username: vIrikefe

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/actual-values/QUSnvJzsywY

I have successfully added targets but been trying to add actual values to no avail. The page just keeps loading.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595532097483126981.png )

**Comment by adrianq** [comment]
This is the same bug that we acknowledged in https://app.gitkraken.com/glo/view/card/c44d50c048d84e118c8ead679316f924 This will be fixed in the next release. We have temporary fixed the problem in this project 'SPC Water for Life Project' both for Actual and Target. Note, however, this problem will raise again on any new project created by a user that is not part of the PM Admin group.
