### ISSUE TITLE
[User feedback] Layout of Screen for Indicator Selection

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#172]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

The sectors are appearing above indicators instead of to the left.  This is not as user-friendly as how it was before.  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596114818632721324.png )

**Comment by adrianq** [comment]
This is a behaviour that happens when the screen (and/or the resolution) is too small to fit all the content on the screen. It can not place the sector bar on the left side and move it to the top. We can try to find mechanisms to keep the bar on the left side for smaller screens but eventually, it will go to the top anyway

**Comment by adrianq** [comment]
Closing this as we already discussed in our latest meeting. We can always reopen it later on if needed...
